Csb 1588563466617
jtessler/studio-multiplayer-game pull request #29
Opened 2020-06-03 21:00 UTC by jalvarez2016

2020-06-03 21:01 UTC, jalvarez2016 commented
merged onto main branch

2020-06-04 18:00 UTC, jtessler requested changes
This looks awesome, Jason! Excellent work!

I just have some comments to keep our code as clean as possible and not check in any unused code. Let me know if you need any help with this review. You can reach out to me on Slack!

2020-06-04 18:00 UTC, jtessler commented on .codesandbox/workspace.json
> +}
Please remove this file from this pull request. We don't need to keep Code Sandbox settings around. :smile:

2020-06-04 18:00 UTC, jtessler commented on src/GameComponent.js
> +import React from "react";
Please revert changes to this base class. Looks like an auto-formatter, but you shouldn't need to touch this file in this pull request.

2020-06-04 18:00 UTC, jtessler commented on src/gameData.js
> +  }
Please only include this entry and the import line in this pull request (and not the other edits). Looks like the auto-formatter in Code Sandbox hates my style. :stuck_out_tongue:

2020-06-04 18:00 UTC, jtessler commented on src/games/SpaceInvaders/SpaceInvaders.jsx
> +      playerNames: UserApi.getName(this.getSessionUserIds()),
It doesn't look like you use `playerNames` anywhere. Delete it?

2020-06-04 18:00 UTC, jtessler commented on src/games/SpaceInvaders/SpaceInvaders.jsx
> +    // if (this.isCreator()) {
Why did you remove this `isCreator()` check? This means both player one and two send the same `newEnemies` list to Firebase, which might lead to problems. I think it makes sense for only the game creator to send this data to Firebase.

2020-06-04 18:00 UTC, jtessler commented on src/games/SpaceInvaders/PlanetHealth.jsx
> +class PlanetHealthBar extends React.Component {
Where is this component used? Can it be deleted?

2020-06-04 18:00 UTC, jtessler commented on src/games/SpaceInvaders/enemyCollide.jsx
> +function enemyCollide(enemy, shots) {
Is `enemyCollide(...)` used anywhere? Please remove this file if not.

2020-06-10 01:17 UTC, jtessler commented
As discussed offline, I merged this manually from [another repo] in [this commit].

[another repo]:https://github.com/MLGpepe01/SpaceInvaders
[this commit]:https://github.com/jtessler/studio-multiplayer-game/commit/382b4f7f60b91e87ce57440fb5869ee344d90c03

2020-06-10 01:17 UTC, closed without merging